"""Generate lffirmware/known_images.py from the local FAMC firmware archive.

Scans every `*_FIRM.syx` under reference/Liquid Foot/Firmware/ (plus any extra roots given on
the command line, e.g. a scratch dir of extracted archive zips), validates the wire header,
and emits a SHA-256 allowlist mapping hash -> (model, version, size).

Only the *hashes* ship publicly — the firmware images themselves are FAMC's and stay local.
Run from the repo root:  python scripts/gen_firmware_db.py [extra_root ...]
"""
import hashlib
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
ROOTS = [REPO / "reference" / "Liquid Foot" / "Firmware"]
ROOTS += [pathlib.Path(p) for p in sys.argv[1:]]

HEADER = bytes([0xF0, 0x00, 0x00, 0x7C, 0x08, 0x06])

MODEL_PAT = {
    "LF+MINI": "Mini",
    "LF+12+": "12+",     # checked before LF+12 (longest match first below)
    "LF+12": "12",
    "LF+JR+": "JR+",
    "LF+PRO+": "Pro+",
}

VER_PAT = re.compile(r"[vV](\d)[._](\d{2})(?:_?(beta|pre))?")


def model_from_name(name: str) -> str | None:
    for key in sorted(MODEL_PAT, key=len, reverse=True):
        if name.upper().startswith(key):
            return MODEL_PAT[key]
    return None


def version_from_path(p: pathlib.Path) -> str:
    for part in reversed(p.parts[:-1]):
        m = VER_PAT.search(part)
        if m:
            v = f"{m.group(1)}.{m.group(2)}"
            return f"{v}-{m.group(3)}" if m.group(3) else v
    return "?"


def main() -> None:
    entries = {}
    skipped = []
    for root in ROOTS:
        if not root.exists():
            continue
        for p in sorted(root.rglob("*FIRM*.syx")):
            data = p.read_bytes()
            if not data.startswith(HEADER) or data[-1] != 0xF7 or data.count(0xF7) != 1:
                skipped.append(f"{p} (bad header/frame)")
                continue
            body = data[6:-1]
            if any(b > 0x7F for b in body):
                skipped.append(f"{p} (invalid sysex data byte >0x7F)")
                continue
            # payload is nibble-encoded apart from a couple of raw header bytes
            if sum(b <= 0x0F for b in body) / len(body) < 0.99:
                skipped.append(f"{p} (payload not predominantly nibbles)")
                continue
            model = model_from_name(p.name)
            if model is None:
                skipped.append(f"{p} (unknown model in filename)")
                continue
            sha = hashlib.sha256(data).hexdigest()
            ver = version_from_path(p)
            prev = entries.get(sha)
            if prev and prev[:2] != (model, ver):
                # same bytes seen under two labels — keep the first, note the clash
                skipped.append(f"{p} (duplicate hash, first seen as {prev[0]} v{prev[1]})")
                continue
            entries[sha] = (model, ver, len(data))

    out = REPO / "lffirmware" / "known_images.py"
    lines = [
        '"""SHA-256 allowlist of known-good FAMC LF+ firmware images.',
        "",
        "GENERATED by scripts/gen_firmware_db.py from the local firmware archive — do not edit.",
        "Maps sha256 -> (model, version, file size). The images themselves are FAMC's and are",
        'not part of this repo; only their hashes are, so the loader can verify a user-supplied',
        'file is a genuine, model-correct release."""',
        "",
        "KNOWN_IMAGES: dict[str, tuple[str, str, int]] = {",
    ]
    for sha, (model, ver, size) in sorted(entries.items(), key=lambda kv: (kv[1][0], kv[1][1])):
        lines.append(f'    "{sha}": ("{model}", "{ver}", {size}),')
    lines.append("}")
    lines.append("")
    out.write_text("\n".join(lines))
    print(f"wrote {out} — {len(entries)} known images")
    models = {}
    for model, ver, _ in entries.values():
        models.setdefault(model, set()).add(ver)
    for m in sorted(models):
        print(f"  {m}: {len(models[m])} versions ({min(models[m])} … {max(models[m])})")
    if skipped:
        print(f"skipped {len(skipped)}:")
        for s in skipped[:10]:
            print("  ", s)


if __name__ == "__main__":
    main()
